---
- hosts: localhost
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    vmware_guest:
      hostname: 10.41.0.12
      username: root
      password: Asi.2019
      validate_certs: no
      folder: /ha-datacenter/vm/
      name: "{{ vmname }}"
      state: poweredon
      guest_id: centos64Guest
      disk:
      - size_gb: 30
        type: thin
        datastore: CHMUDSV001
      hardware:
        memory_mb: 4096
        num_cpus: 4
      networks:
      - name: VM Network
        type: dhcp
        device_type: vmxnet3
        dns_servers:
        - 10.41.0.10
      customization:
        dns_servers:
        - 10.41.0.10
      cdrom:
        type: iso
        iso_path: "[CHMUDSV001] ISO/centos-ks.iso"
    delegate_to: localhost
    register: deploy_vm